{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "자원 사용량 메트릭: UPTIME, cpu, memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "서비스 성능 메트릭: 처리량, 에러율", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "처리량(Throughput)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(promhttp_metric_handler_requests_total) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "에러율(Error Rate)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(promhttp_metric_handler_requests_total{code=~\"5..\"}) by (instance) / sum(promhttp_metric_handler_requests_total) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB 관련 ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "초당 쿼리 수 (QPS)",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[1m])\nor rate(redis_commands_processed_total[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "네트워크 대역폭 / 노드수 / 로드밸런싱 ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "동시 접속자 수",
   "type": "timeseries",
   "description": " 연결 상태(Established) : 서버의 동시 접속 클라이언트 수를 대략적으로 추정",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab\nor redis_connected_clients",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}