version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - coupon-network
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - coupon-network
    ports:
      - 3000:3000
    volumes:
      - ./grafana/volume:/var/lib/grafana
    restart: always

networks:
  coupon-network:
    name: coupon-network
    external: true  # 기존 네트워크 사용, 별도 host.docker.internal 접근 제거