global:
  scrape_interval: 5s                             # 주기 (적당한 interval?)

scrape_configs:
  - job_name: 'kakao-be-jvm'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['kakao-be:8080']                # 명시적으로 컨테이너 네트워크만 사용

  - job_name: 'kakao-be-exporter'
    static_configs:
      - targets: [ 'kakao-be:9100' ]

  - job_name: 'coupon-api-jvm'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['coupon-api:8081']

  - job_name: 'coupon-api-exporter'
    static_configs:
      - targets: ['coupon-api:9100']

  - job_name: 'coupon-consumer-jvm'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['coupon-consumer:8082']

  - job_name: 'coupon-consumer-exporter'
    static_configs:
      - targets: [ 'coupon-consumer:9100' ]

  - job_name: "mysql-exporter"                    # MySQL 메트릭 수집
    static_configs:
      - targets: [ 'mysqld-exporter:9104' ]

  - job_name: "redis-exporter"                    # 레디스 메트릭 수집
    static_configs:
      - targets: [ 'redis-exporter:9121' ]

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']          # Nginx Exporter 연결
