global:
  scrape_interval: 5s                             # 주기 (적당한 interval)

scrape_configs:
  - job_name: 'coupon-APP'
    static_configs:
      - targets: ['coupon-api:9100']
      - targets: ['coupon-consumer:9100']

  - job_name: 'shop-APP'
    static_configs:
      - targets: ['kakao-fe:9113']          # Nginx Exporter 연결
      - targets: ['kakao-be:9100']

  - job_name: "mysql"                      # MySQL 메트릭 수집
    static_configs:
      - targets: [ 'mysqld-exporter:9104' ]

  - job_name: "redis"                     # 레디스 메트릭 수집
    static_configs:
      - targets: [ 'redis-exporter:9121' ]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'
rule_files:
  - "alerts.yml"
